- id: '1684746714869'
  alias: Set Feed In First
  description: change inverter work mode to Feed In First
  trigger:
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41000
      slave: 247
      value: 1
  mode: single
- id: '1684746814312'
  alias: Set Self Use
  description: change inverter work mode to Self Use
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41000
      slave: 247
      value: 0
  mode: single
- id: '1685023611778'
  alias: Set G98 Export Limit
  description: change inverter export limit to 3.68kW
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41012
      slave: 247
      value: 3680
  mode: single
- id: '1685023679841'
  alias: Set G99 Export Limit
  description: change inverter export limit to 6kW
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41012
      slave: 247
      value: 6000
  mode: single
- id: '1685023771341'
  alias: Set Max Charge Current 25A
  description: change max charge current to 25A
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41007
      slave: 247
      value: 250
  mode: single
- id: '1685023877031'
  alias: Set Max SoC 100%
  description: change max SoC to 100%
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      address: 41010
      slave: 247
      value: 100
      hub: FoxESSInverterModbus
  mode: single
- id: '1685024207064'
  alias: Set Max Charge Current 15A
  description: change max charge current to 15A
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41007
      slave: 247
      value: 150
  mode: single
- id: '1685024237616'
  alias: Set Max SoC 50%
  description: change max SoC to 50%
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      address: 41010
      slave: 247
      hub: FoxESSInverterModbus
      value: 50
  mode: single
- id: '1685032746831'
  alias: Reset Password
  description: change inverter password to 0000
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 40013
      slave: 247
      value: 0
  mode: single
- id: '1685265384959'
  alias: Charge from Grid 2am to 5am
  description: Set charge between 2am and 5am
  triggers: []
  conditions: []
  actions:
  - data:
      hub: FoxESSInverterModbus
      address: 41001
      slave: 247
      value:
      - 0
      - 512
      - 1280
      - 0
      - 0
      - 0
    action: modbus.write_register
  mode: single
- id: '1685266798577'
  alias: Disable Charge from Grid
  description: Set time period 1 to 00:00 - 00:00
  triggers: []
  conditions: []
  actions:
  - data:
      hub: FoxESSInverterModbus
      address: 41001
      slave: 247
      value:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    action: modbus.write_register
  mode: single
- id: '1685267956539'
  alias: Set Min SoC to 10%
  description: change min SoC to 10%
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41009
      slave: 247
      value: 10
  mode: single
- id: '1685268004260'
  alias: Set Min SoC (On Grid) to 10%
  description: change Min SoC (On Grid) to 10%
  triggers: []
  conditions: []
  actions:
  - data:
      hub: FoxESSInverterModbus
      address: 41011
      slave: 247
      value: 10
    action: modbus.write_register
  mode: single
- id: '1686476265795'
  alias: Set Export Limit
  description: change inverter export limit
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41012
      slave: 247
      value: 3600
  mode: single
- id: '1686652252779'
  alias: Renew Certificate
  description: Daily check if SSL certificate needs to be renewed
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - service: hassio.addon_start
    data:
      addon: core_letsencrypt
  mode: single
- id: '1686653226368'
  alias: Restart NGINX
  description: Restart NGINX to pick up any renewed certificates
  trigger:
  - platform: time
    at: 03:00:00
  condition: []
  action:
  - service: hassio.addon_restart
    data:
      addon: core_nginx_proxy
  mode: single
- id: '1686752049218'
  alias: Set Max Charge Current to 5A
  description: change max charge current to 5A
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41007
      slave: 247
      value: 50
  mode: single
- id: '1691342611707'
  alias: Upload pvoutput data every hour
  trigger:
  - platform: time_pattern
    minutes: '59'
  action:
  - service: rest_command.pvoutput_upload
    data: {}
  mode: single
- id: '1712678883739'
  alias: System Disable
  description: Set System Enable to 0
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41013
      slave: 247
      value: 0
  mode: single
- id: '1712678959626'
  alias: System Enable
  description: Set System Enable to 1
  trigger: []
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: FoxESSInverterModbus
      address: 41013
      slave: 247
      value: 1
  mode: single
- id: '1738665422459'
  alias: Remote Control Start
  description: Start remote control charge / discharge
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.remote_enable
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - data:
      hub: FoxESSInverterModbus
      address: 44000
      slave: 247
      value: 1
    action: modbus.write_register
  - data:
      hub: FoxESSInverterModbus
      address: 44001
      slave: 247
      value: '{% set seconds = (states(''input_number.remote_time'') | int(default=1))
        * 60 %} {{ seconds }}'
    action: modbus.write_register
  - data:
      hub: FoxESSInverterModbus
      address: 44002
      slave: 247
      value: '{% set power = (states(''input_number.remote_power'') | float(default=0)
        * 1000) | int %} {{ (65536 + power) if power < 0 else power }}'
    action: modbus.write_register
  mode: single
- id: '1738687203008'
  alias: Remote Control Stop
  description: Stop remote control command
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.remote_enable
    from: 'on'
    to: 'off'
  conditions: []
  actions:
  - data:
      hub: FoxESSInverterModbus
      address: 44000
      slave: 247
      value: 0
    action: modbus.write_register
  mode: single
