# Source https://github.com/TonyM1958/HA-FoxESS-Modbus
# this is not a valid configuration file!
# Add what follows into your configuration.yaml
#

#-----------------------------------------------------------------------------
# START: HA-FoxESS-Modbus configuration
#-----------------------------------------------------------------------------
# If you have a complex HA setup and already have any sections with these names,
# create a local include file in your CONFIG folder, merge the contents of the
# relevant file and reference your local include here.

# Select a modbus file to match your inverter and connection. Change XX to H1, H1G2, KH or H3
modbus: !include custom_components/HA-FoxESS-Modbus/modbusXX_RS485_LAN.yaml
#modbus: !include custom_components/HA-FoxESS-Modbus/modbusXX_RS485.yaml

# Select a template to matches your inverter
template: !include custom_components/HA-FoxESS-Modbus/template.yaml
#template: !include custom_components/HA-FoxESS-Modbus/templateH1G2.yaml

# Riemann sum and utility meters
sensor: !include custom_components/HA-FoxESS-Modbus/sensor.yaml
utility_meter: !include custom_components/HA-FoxESS-Modbus/utility_meter.yaml

# recorder settings to keep history for 30 days in HA or Maria database
recorder: !include custom_components/HA-FoxESS-Modbus/recorder_ha.yaml
#recorder: !include custom_components/HA-FoxESS-Modbus/recorder_maria.yaml

# optional upload generation and consumption data to pvoutput
rest_command: !include custom_components/HA-FoxESS-Modbus/rest_command.yaml

# input values for configuring integration:
input_number: !include custom_components/HA-FoxESS-Modbus/input_number.yaml
input_datetime: !include custom_components/HA-FoxESS-Modbus/input_datetime.yaml
#-----------------------------------------------------------------------------
# END: HA-FoxESS-Modbus configuration
#-----------------------------------------------------------------------------
